services:
  db:
    image: 'postgres:17.2'
    environment:
      - POSTGRES_DB=lovify
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
    ports:
      - '5433:5432'
    networks:
      - db

  s3:
    image: 'bitnami/minio:2024.12.18'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio_root_user
      - MINIO_ROOT_PASSWORD=minio_root_password
    networks:
      - s3

networks:
  db:
  s3: